#!/bin/busybox sh
busybox dmesg -n 1
/bin/busybox --install -s
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
busybox mdev -s
echo "It seems that initramfs is missing! Dropping to a shell..."
exec /linuxrc
