#!/bin/sh

################################
#                              #
# mkinitrd, Version 0.10       #
# Creada en 28-09-2020         #
# PocketNES Software (gpl)2020 #
#                              #
################################

init(){
	echo "* Inicializando tempdir at $1..."
	cd $1
	mkdir -p $1/workdir
	mkdir -p $1/initramfs
	cp $init $1/workdir
	cp $busybox $1/workdir/busybox
}

create_fs(){
	echo "* Creando sistema de archivos:"
	for i in bin dev sbin proc sys usr/bin usr/sbin; do
		echo "	# initramfs/$i"
		mkdir -p initramfs/$i
	done
	mv workdir/busybox initramfs/bin
	mv workdir/init initramfs
	mknod initramfs/dev/console c 5 1
	mknod initramfs/dev/tty c 5 0
	mknod initramfs/dev/null c 1 3
}

create_ar(){
	echo "* Creando archivo de initramfs..."
	cd initramfs
	find . | cpio -o --format=newc > ../initramfs.cpio
	cd ..
	case $compression in
		"gzip")
			gzip initramfs.cpio
			ext=".gz"
			;;
		"bzip2")
			bzip2 initramfs.cpio
			ext=".bz2"
			;;
		"xz")
			xz --check=crc32 initramfs.cpio
			ext=".xz"
			;;
	esac
}

echo "mkinitrd, Version 0.10"
echo -e "(c) 2020 PocketNES Software, debajo GPLv3\n"

if [ $(id -u) -ne 0 ]; then
	echo "Error: No eres root. Tienes que ser root para utilizar esta herramienta"
	exit 1
fi

#Chequea todos los parametros
while [ $# -gt 0 ]; do
	case $1 in
		--busybox)
			shift
			busybox=$1
			;;
		--init)
			shift
			init=$1
			;;
		--type)
			shift
			type=$1
			;;
		--compression)
			shift
			compression=$1
			;;
		--help)
			echo "mkinitrd es un script que crea ramdisks iniciales. Aqui estan algunas de las opciones"
			echo "que le puedes dar al script:\n"
			echo "--busybox	La ruta de BusyBox"
			echo "--init		La ruta del script de init"
			echo "--type		Define el tipo de initrd (rd, ramfs)"
			echo "--compression	Define el tipo de compresion (gzip, bzip2, xz)"
			echo "--help		Mostrar esta ayuda\n"
			exit 0
			;;
		*)
			echo "Error: Parametro desconoscido '$1'. Escriba $0 --help para mostrar ayuda."
			exit 1
	esac
	shift
done

#Chequea parametros requeridos
if [ "$busybox" = "" ]; then
	echo "Error: --busybox es requirido."
	exit 2
elif [ "$init" = "" ]; then
	echo "Error: --init es requirido."
	exit 2
fi

pwd=$(pwd)
tempdir=$(mktemp -dt pls-XXXXXX)

init $tempdir
create_fs
create_ar
mv initramfs.cpio$ext $pwd
rm -rf $tempdir
